### ISSUE TITLE
如何添加自定义模板以及模板中的type如果为load-balance无法正常转换。

### ISSUE THREAD

**Issue by Depressboy** [nitezs/sub2clash#11]
第一个问题：使用的是docker安装方式，把自定义模板放到/app/template目录下然后在网页中输入名称并不起作用，尝试更改自定义模板文件名为默认模板的文件名能正常使用。

第二个问题：将自定义模板中的type选项设定成load-balance（负载均衡）后，输出的规则中显示为null，具体如下：

正常设置的模板：
proxy-groups:
  - name: ⚖️ 负载均衡-散列
    type: load-balance
    url: http://www.google.com/generate_204
    interval: 300
    strategy: consistent-hashing
    proxies:
      - <countries>
  - name: ⚖️ 负载均衡-轮询
    type: load-balance
    url: http://www.google.com/generate_204
    interval: 300
    strategy: round-robin
    proxies:
      - <countries>
  - name: 🚀 节点选择
    type: select
    proxies:
      - ⚖️ 负载均衡-散列
      - ⚖️ 负载均衡-轮询
      - ♻️ 自动选择
      - <countries>
      - 🚀 手动切换
      - DIRECT

实际输出的模板：
proxy-groups:
    - null
    - null
    - name: "\U0001F680 节点选择"
      type: select
      proxies:
        - ⚖️ 负载均衡-散列
        - ⚖️ 负载均衡-轮询
        - ♻️ 自动选择
        - 德国(DE)
        - 法国(FR)
        - 荷兰(NL)
        - 美国(US)
        - 日本(JP)
        - 台湾(TW)
        - 新加坡(SG)
        - "\U0001F680 手动切换"
        - DIRECT

另外还有个不是问题的问题，输出后不能正常显示emoji图标，上面也能看到，不过在clash控制面板里面显示正常，不知道为啥，不修复也无所谓了

**Comment by nitezs** [comment]
1. [50877b1691dfb29077902a5383767e412f1361c0](https://github.com/nitezs/sub2clash/commit/50877b1691dfb29077902a5383767e412f1361c0)
2. [3616ae870a8d1eb3d03b84ea4b9dc84c4c6d603f](https://github.com/nitezs/sub2clash/commit/3616ae870a8d1eb3d03b84ea4b9dc84c4c6d603f)
3. \UXXX 是 emoji 的另一种表示形式，不用在意

**Comment by Depressboy** [comment]
感谢大佬修复，已测试能够正常转换，模板也能正常识别。
另外还有发现了个小问题，就是转换页面下方的“复制链接”按钮好像没有作用，点击了并没有复制到，只能手动复制

另外还有一个功能建议，就是转换模板的时候把机场的订阅信息保留下来，这样在openclash里面能方便查看流量剩余，如下图
![1](https://github.com/nitezs/sub2clash/assets/26180798/dc76a09b-2c5d-4d67-a9da-f5a3c1100ce7)

第三行是使用了本地转换后显示无订阅信息，不知道能不能保留下来。

再次感谢大佬制作的转换工具，现在的在线转换都不支持vless转换。

**Comment by nitezs** [comment]
> 感谢大佬修复，已测试能够正常转换，模板也能正常识别。 另外还有发现了个小问题，就是转换页面下方的“复制链接”按钮好像没有作用，点击了并没有复制到，只能手动复制
> 
> 另外还有一个功能建议，就是转换模板的时候把机场的订阅信息保留下来，这样在openclash里面能方便查看流量剩余，如下图 ![1](https://private-user-images.githubusercontent.com/26180798/305141440-dc76a09b-2c5d-4d67-a9da-f5a3c1100ce7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwNTUzNDUsIm5iZiI6MTcwODA1NTA0NSwicGF0aCI6Ii8yNjE4MDc5OC8zMDUxNDE0NDAtZGM3NmEwOWItMmM1ZC00ZDY3LWE5ZGEtZjVhM2MxMTAwY2U3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE2VDAzNDQwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyYTJhZGRlZWEzMjkxY2IxMWM5OGQxZDA5ZTY4NWU1ZTU5NjE1NmQ1NzcwNGVkM2VmYTE2YTM1NmExMWQwZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T0rWUiJQRqHz1pDvwZbfoCzRxbb2u454zgpA70j4Dbo)
> 
> 第三行是使用了本地转换后显示无订阅信息，不知道能不能保留下来。
> 
> 再次感谢大佬制作的转换工具，现在的在线转换都不支持vless转换。

我使用Chrome复制链接功能是正常的，可能别的浏览器有兼容问题。
我不太清楚这个保留订阅信息是什么意思，在配置中的哪一部分是给客户端读取的机场信息呢？

**Comment by tanmoumou252** [comment]
> > 感谢大佬修复，已测试能够正常转换，模板也能正常识别。 另外还有发现了个小问题，就是转换页面下方的“复制链接”按钮好像没有作用，点击了并没有复制到，只能手动复制
> > 另外还有一个功能建议，就是转换模板的时候把机场的订阅信息保留下来，这样在openclash里面能方便查看流量剩余，如下图 ![1](https://private-user-images.githubusercontent.com/26180798/305141440-dc76a09b-2c5d-4d67-a9da-f5a3c1100ce7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwNTUzNDUsIm5iZiI6MTcwODA1NTA0NSwicGF0aCI6Ii8yNjE4MDc5OC8zMDUxNDE0NDAtZGM3NmEwOWItMmM1ZC00ZDY3LWE5ZGEtZjVhM2MxMTAwY2U3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE2VDAzNDQwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyYTJhZGRlZWEzMjkxY2IxMWM5OGQxZDA5ZTY4NWU1ZTU5NjE1NmQ1NzcwNGVkM2VmYTE2YTM1NmExMWQwZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T0rWUiJQRqHz1pDvwZbfoCzRxbb2u454zgpA70j4Dbo)
> > 第三行是使用了本地转换后显示无订阅信息，不知道能不能保留下来。
> > 再次感谢大佬制作的转换工具，现在的在线转换都不支持vless转换。
> 
> 我使用Chrome复制链接功能是正常的，可能别的浏览器有兼容问题。 我不太清楚这个保留订阅信息是什么意思，在配置中的哪一部分是给客户端读取的机场信息呢？

就是流量的使用情况,这是一段以前的CFW文档里的信息,不清楚 $\color{#FF0000}{mihomo}$ 的[文档](https://wiki.metacubex.one)里有没有具体的信息,但是 $\color{#FF0000}{mihomo}$ 支持这个特性
```yaml
#parsers: # array
  - reg: '分组简化版本地配置-填订阅.yml'
    code: |
      module.exports.parse = async (raw, { axios, yaml, notify, console }) => {
        raw = raw.replace(/# upload=\d*; download=\d*; total=\d*; expire=\d*;*\n/gm,'')
        const url = '此处填订阅'
        let { headers:{"subscription-userinfo": si = ""}={}, status } = await axios.head(url)
        si = si.replace(/;*$/g,'')
        if (status === 200 && si) {
          return `# ${si};\n${raw}`
        }
        return raw
      }
#上述代码为本地配置预处理代码，目的是在本地配置下方显示流量使用情况  
#文档中称其为：订阅信息 subscription-userinfo  
#可使用curl -I 'https://example.com/subscription_url'来查看订阅是否带有流量信息)  
```

![图片](https://github.com/nitezs/sub2clash/assets/118299342/1e76f98b-5bfc-4076-885e-5f08a1c00fc1)

**Comment by nitezs** [comment]
> > > 感谢大佬修复，已测试能够正常转换，模板也能正常识别。 另外还有发现了个小问题，就是转换页面下方的“复制链接”按钮好像没有作用，点击了并没有复制到，只能手动复制
> > > 另外还有一个功能建议，就是转换模板的时候把机场的订阅信息保留下来，这样在openclash里面能方便查看流量剩余，如下图 ![1](https://private-user-images.githubusercontent.com/26180798/305141440-dc76a09b-2c5d-4d67-a9da-f5a3c1100ce7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwNTUzNDUsIm5iZiI6MTcwODA1NTA0NSwicGF0aCI6Ii8yNjE4MDc5OC8zMDUxNDE0NDAtZGM3NmEwOWItMmM1ZC00ZDY3LWE5ZGEtZjVhM2MxMTAwY2U3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE2VDAzNDQwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyYTJhZGRlZWEzMjkxY2IxMWM5OGQxZDA5ZTY4NWU1ZTU5NjE1NmQ1NzcwNGVkM2VmYTE2YTM1NmExMWQwZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T0rWUiJQRqHz1pDvwZbfoCzRxbb2u454zgpA70j4Dbo)
> > > 第三行是使用了本地转换后显示无订阅信息，不知道能不能保留下来。
> > > 再次感谢大佬制作的转换工具，现在的在线转换都不支持vless转换。
> > 
> > 
> > 我使用Chrome复制链接功能是正常的，可能别的浏览器有兼容问题。 我不太清楚这个保留订阅信息是什么意思，在配置中的哪一部分是给客户端读取的机场信息呢？
> 
> 就是流量的使用情况,这是一段以前的CFW文档里的信息,不清楚 mihomo 的[文档](https://wiki.metacubex.one)里有没有具体的信息,但是 mihomo 支持这个特性
> 
> ```yaml
> #parsers: # array
>   - reg: '分组简化版本地配置-填订阅.yml'
>     code: |
>       module.exports.parse = async (raw, { axios, yaml, notify, console }) => {
>         raw = raw.replace(/# upload=\d*; download=\d*; total=\d*; expire=\d*;*\n/gm,'')
>         const url = '此处填订阅'
>         let { headers:{"subscription-userinfo": si = ""}={}, status } = await axios.head(url)
>         si = si.replace(/;*$/g,'')
>         if (status === 200 && si) {
>           return `# ${si};\n${raw}`
>         }
>         return raw
>       }
> #上述代码为本地配置预处理代码，目的是在本地配置下方显示流量使用情况  
> #文档中称其为：订阅信息 subscription-userinfo  
> #可使用curl -I 'https://example.com/subscription_url'来查看订阅是否带有流量信息)  
> ```
> 
> ![图片](https://private-user-images.githubusercontent.com/118299342/306166347-1e76f98b-5bfc-4076-885e-5f08a1c00fc1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2MjAzOTgsIm5iZiI6MTcwODYyMDA5OCwicGF0aCI6Ii8xMTgyOTkzNDIvMzA2MTY2MzQ3LTFlNzZmOThiLTViZmMtNDA3Ni04ODVlLTVmMDhhMWMwMGZjMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMlQxNjQxMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZGQyMDk4YjliZmQwM2M3YjZhNzZkZjk5NzgxOTVjYzA1OGIxNTZjZTlhMGI3ZDBhMmUwOTc3NjhiM2Q1MDkyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.EeoWpkWGmC-3IhACci-s8nZkmf1JT-gq5NDHXDKR5NI)


没有找到相关文档，你发的这个也没太看懂

**Comment by tanmoumou252** [comment]
> > > > 感谢大佬修复，已测试能够正常转换，模板也能正常识别。 另外还有发现了个小问题，就是转换页面下方的“复制链接”按钮好像没有作用，点击了并没有复制到，只能手动复制
> > > > 另外还有一个功能建议，就是转换模板的时候把机场的订阅信息保留下来，这样在openclash里面能方便查看流量剩余，如下图 ![1](https://private-user-images.githubusercontent.com/26180798/305141440-dc76a09b-2c5d-4d67-a9da-f5a3c1100ce7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwNTUzNDUsIm5iZiI6MTcwODA1NTA0NSwicGF0aCI6Ii8yNjE4MDc5OC8zMDUxNDE0NDAtZGM3NmEwOWItMmM1ZC00ZDY3LWE5ZGEtZjVhM2MxMTAwY2U3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE2VDAzNDQwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyYTJhZGRlZWEzMjkxY2IxMWM5OGQxZDA5ZTY4NWU1ZTU5NjE1NmQ1NzcwNGVkM2VmYTE2YTM1NmExMWQwZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T0rWUiJQRqHz1pDvwZbfoCzRxbb2u454zgpA70j4Dbo)
> > > > 第三行是使用了本地转换后显示无订阅信息，不知道能不能保留下来。
> > > > 再次感谢大佬制作的转换工具，现在的在线转换都不支持vless转换。
> > > 
> > > 
> > > 我使用Chrome复制链接功能是正常的，可能别的浏览器有兼容问题。 我不太清楚这个保留订阅信息是什么意思，在配置中的哪一部分是给客户端读取的机场信息呢？
> > 
> > 
> > 就是流量的使用情况,这是一段以前的CFW文档里的信息,不清楚 mihomo 的[文档](https://wiki.metacubex.one)里有没有具体的信息,但是 mihomo 支持这个特性
> > ```yaml
> > #parsers: # array
> >   - reg: '分组简化版本地配置-填订阅.yml'
> >     code: |
> >       module.exports.parse = async (raw, { axios, yaml, notify, console }) => {
> >         raw = raw.replace(/# upload=\d*; download=\d*; total=\d*; expire=\d*;*\n/gm,'')
> >         const url = '此处填订阅'
> >         let { headers:{"subscription-userinfo": si = ""}={}, status } = await axios.head(url)
> >         si = si.replace(/;*$/g,'')
> >         if (status === 200 && si) {
> >           return `# ${si};\n${raw}`
> >         }
> >         return raw
> >       }
> > #上述代码为本地配置预处理代码，目的是在本地配置下方显示流量使用情况  
> > #文档中称其为：订阅信息 subscription-userinfo  
> > #可使用curl -I 'https://example.com/subscription_url'来查看订阅是否带有流量信息)  
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![图片](https://private-user-images.githubusercontent.com/118299342/306166347-1e76f98b-5bfc-4076-885e-5f08a1c00fc1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2MjAzOTgsIm5iZiI6MTcwODYyMDA5OCwicGF0aCI6Ii8xMTgyOTkzNDIvMzA2MTY2MzQ3LTFlNzZmOThiLTViZmMtNDA3Ni04ODVlLTVmMDhhMWMwMGZjMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMlQxNjQxMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZGQyMDk4YjliZmQwM2M3YjZhNzZkZjk5NzgxOTVjYzA1OGIxNTZjZTlhMGI3ZDBhMmUwOTc3NjhiM2Q1MDkyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.EeoWpkWGmC-3IhACci-s8nZkmf1JT-gq5NDHXDKR5NI)
> 
> 没有找到相关文档，你发的这个也没太看懂

害,早点休息吧[doge]
