### ISSUE TITLE
不自持vless和reality吗

### ISSUE THREAD

**Issue by hausen1012** [nitezs/sub2clash#15]

**Comment by nitezs** [comment]
试一下dev版的docker镜像

**Comment by hausen1012** [comment]
> 试一下dev版的docker镜像

似乎也还是不行，提供的预览链接也不支持

**Comment by nitezs** [comment]
> > 试一下dev版的docker镜像
> 
> 似乎也还是不行，提供的预览链接也不支持

配置缺了什么字段吗？

**Comment by hausen1012** [comment]
我是拿来就用的，填了订阅地址或者是节点地址，还需要什么特殊配置吗？

**Comment by hausen1012** [comment]
> > 我是拿来就用的，填了订阅地址或者是节点地址，还需要什么特殊配置吗？
> 
> 程序生成的配置和正确配置有什么差别

不显示vless和reality节点，即使指定了模板template_meta.yaml

**Comment by hausen1012** [comment]
找到原因了，对不起，是我的问题，非常感谢！！！辛苦了
