### ISSUE TITLE
大佬，打扰了，麻烦你看看

### ISSUE THREAD

**Issue by hausen1012** [nitezs/sub2clash#17]
![1709975416096.png](https://lsky.153224.xyz/i/2024/03/09/65ec2779eafe6.png)

用的自己的模板，太长了发不出

**Comment by nitezs** [comment]
评论可以发文件，我需要看看模板才能知道问题在哪

**Comment by hausen1012** [comment]
[template_meta.txt](https://github.com/nitezs/sub2clash/files/14545771/template_meta.txt)
改了一下hou'z后缀才能发

**Comment by nitezs** [comment]
模板是需要修改来满足程序标准的，你可以参考 https://github.com/nitezs/sub2clash/blob/main/templates/template_meta.yaml
```
<all> 为添加所有节点
<countries> 为添加所有国家策略组
<地区二位字母代码> 为添加指定地区所有节点，例如 <hk> 将添加所有香港节点
```

**Comment by hausen1012** [comment]
已经按照提示添加了 all 选项，还是有同样的问题
[template_meta.txt](https://github.com/nitezs/sub2clash/files/14545819/template_meta.txt)

**Comment by nitezs** [comment]
> 已经按照提示添加了 all 选项，还是有同样的问题 [template_meta.txt](https://github.com/nitezs/sub2clash/files/14545819/template_meta.txt)

你没有在自动选择增加节点

**Comment by hausen1012** [comment]
好了噢，感谢感谢。

还有一个问题是，点击复制短链或者链接，都不能自动复制到剪贴板，不知道是不是我设备的问题。

另外可以增加节点更新了，短链不改变的功能吗？这个在有多个客户端的时候非常有用呢，不用全部都去替换链接。

再次感谢大佬，您这个不像他们的那个那么复杂，需要两三个容器才能实现订阅转换，短链功能， 对我而言刚好。

**Comment by nitezs** [comment]
> 好了噢，感谢感谢。
> 
> 还有一个问题是，点击复制短链或者链接，都不能自动复制到剪贴板，不知道是不是我设备的问题。
> 
> 另外可以增加节点更新了，短链不改变的功能吗？这个在有多个客户端的时候非常有用呢，不用全部都去替换链接。
> 
> 再次感谢大佬，您这个不像他们的那个那么复杂，需要两三个容器才能实现订阅转换，短链功能， 对我而言刚好。

不能复制应该是浏览器兼容问题，我使用的是Chrome，之后应该会修
修改短链对应配置的功能我先加到 Todo，有空再做

**Comment by hausen1012** [comment]
哦对，我用的是edge，f12报错。
```
index.js:325  复制到剪贴板失败: TypeError: Cannot read properties of undefined (reading 'writeText')
    at copyToClipboard (index.js:318:35)
    at HTMLButtonElement.onclick ((索引):238:14)
```
那短链的话等大佬您有空！！
