### ISSUE TITLE
使用sub2clash自定义模板后proxies前的配置字段丢失

### ISSUE THREAD

**Issue by QiChaiQiChai** [nitezs/sub2clash#19]
我在使用自定义的配置模板转换后，proxies前的字段并没有生成在最终的转换得到配置文件里，不知道时什么问题，以下是我自己写的配置模板 https://[raw.githubusercontent.com/QiChaiQiChai/sub2clash_configs/main/configs/phone.yaml](https://raw.githubusercontent.com/QiChaiQiChai/sub2clash_configs/main/configs/phone.yaml)

**Comment by nitezs** [comment]
在dev分支修复了这个问题

**Comment by QiChaiQiChai** [comment]
好的，另外请问转换时可以关闭策略组中对节点按照国家分类的策略组吗

**Comment by nitezs** [comment]
> 好的，另外请问转换时可以关闭策略组中对节点按照国家分类的策略组吗

不可以

**Comment by QiChaiQiChai** [comment]
好的，谢谢😀，如果有可能的话希望能在未来支持。
