### ISSUE TITLE
hysteria2转换时名称出现在了sni字段

### ISSUE THREAD

**Issue by QiChaiQiChai** [nitezs/sub2clash#21]
- { name: 香港01|Premium, server: hkp.xjichang.buzz, port: 45570, udp: true, skip-cert-verify: true, sni: kr1.xjichang.buzz, type: hysteria2, password: xxxxxxxx }

转换后变成下面这种形式：
    - type: hysteria2
      name: "1"
      server: hkp.xjichang.buzz
      port: 45570
      password: xxxxxxxx
      sni: "kr1.jichang.buzz#香港01|Premium\r"
      skip-cert-verify: true

**Comment by nitezs** [comment]
从什么格式的字符串转过来的

**Comment by QiChaiQiChai** [comment]
就是我发的最上面一行的yaml格式的配置文件

**Comment by nitezs** [comment]
没有能输入这种格式节点的地方啊

**Comment by nitezs** [comment]
这个是模板里的节点吗

**Comment by QiChaiQiChai** [comment]
是我订阅链接里的节点，转换的时候也是使用的订阅链接，没有单独输入节点

**Comment by QiChaiQiChai** [comment]
我试了试使用encode的订阅链接后发现没有问题了，直接使用订阅链接时出现了上面说的问题，但是如果节点名称时英文的话不需要url encode也可以使用

**Comment by QiChaiQiChai** [comment]
不知道是哪里导致了上面这种问题，如果能修复一下不适应url encode就更好了！

另外或许有考虑加入根据节点名称自动加上国家的emoji这个功能吗，我看在[country_code_map.go](https://github.com/nitezs/sub2clash/blob/main/model/country_code_map.go)里面是有写一些简单的匹配功能的，如果能实现就太好了！！！

**Comment by nitezs** [comment]
> 我试了试使用encode的订阅链接后发现没有问题了，直接使用订阅链接时出现了上面说的问题，但是如果节点名称时英文的话不需要url encode也可以使用

有空我看看

> 不知道是哪里导致了上面这种问题，如果能修复一下不适应url encode就更好了！
> 
> 另外或许有考虑加入根据节点名称自动加上国家的emoji这个功能吗，我看在[country_code_map.go](https://github.com/nitezs/sub2clash/blob/main/model/country_code_map.go)里面是有写一些简单的匹配功能的，如果能实现就太好了！！！

加 emoji 这个功能感觉不是很有必要，不过欢迎PR

**Comment by QiChaiQiChai** [comment]
还有一个问题，就是有一个功能是排除重复节点，我发现会有概率误判，比如说几个hysterica2节点如果只有sni不一样的情况下，所以可以考虑给一个是否开启这个功能的选项吗，想要排除哪个节点使用正则表达式进行精确排除

**Comment by nitezs** [comment]
> 还有一个问题，就是有一个功能是排除重复节点，我发现会有概率误判，比如说几个hysterica2节点如果只有sni不一样的情况下，所以可以考虑给一个是否开启这个功能的选项吗，想要排除哪个节点使用正则表达式进行精确排除

目前是根据 IP+端口+协议 判断节点是否重复的，你可以按需修改代码

**Comment by QiChaiQiChai** [comment]
哈哈哈，我想把那里直接删除
