### ISSUE TITLE
关于不输出国家策略组选项

### ISSUE THREAD

**Issue by tom2almighty** [nitezs/sub2clash#24]
目前勾选`不输出国家策略组` 后，如果其他策略组存在 `<countries>`选项，输出订阅文件中仍然包括国家策略组导致报错，因此`不输出国家策略组`开关能否同时控制国家策略组和其他策略组的引用

**Comment by nitezs** [comment]
如果不输出国家策略组模板中不应该设置 <countries>

**Comment by tom2almighty** [comment]
我明白不添加不会报错。目前的默认模板中策略组是有国家策略组的，所以直接部署下来，如果直接使用，但是选择了不输出，就会报错，个人觉得可以优化一下，如果您认为没必要，请您直接关闭issue。
