### ISSUE TITLE
这个模板这里应该怎么填写

### ISSUE THREAD

**Issue by 277383761** [nitezs/sub2clash#25]
<img width="859" alt="image" src="https://github.com/nitezs/sub2clash/assets/49450669/59f07c31-058b-4344-b354-38a929ff7295">
我只想使用类似这样模板的功能
https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/config/ACL4SSR.ini

**Comment by 277383761** [comment]
顺便说一下,mac下edge浏览器点击复制短连接的按钮,仿佛没有复制上,没效

**Comment by nitezs** [comment]
https://github.com/nitezs/sub2clash/tree/main/templates

**Comment by 277383761** [comment]
> https://github.com/nitezs/sub2clash/tree/main/templates

<img width="705" alt="image" src="https://github.com/nitezs/sub2clash/assets/49450669/0f522a25-9e75-4458-a62f-7138898756d7">

你好,使用template_meta.yaml模板出来后的短链接,放进openclash更新成功,但是运行时报如上截图中的错误

**Comment by 277383761** [comment]
更新到最新版openclash后直接订阅不了了.无法生成新的配置文件了.

**Comment by 277383761** [comment]
能否弄个简单的视频教程.实在是弄不会啊.

**Comment by 277383761** [comment]
可否内置一批ACL4SSR模板列表让我们选择呢?

**Comment by nitezs** [comment]
> > https://github.com/nitezs/sub2clash/tree/main/templates
> 
> <img alt="image" width="705" src="https://private-user-images.githubusercontent.com/49450669/318197277-0f522a25-9e75-4458-a62f-7138898756d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4MDgzNTgsIm5iZiI6MTcxMTgwODA1OCwicGF0aCI6Ii80OTQ1MDY2OS8zMTgxOTcyNzctMGY1MjJhMjUtOWU3NS00NDU4LWE2MmYtNzEzODg5ODc1NmQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMwVDE0MTQxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0MTljYTNiMzczOTU3ZWRkODQ5MzI0Y2U3MDkyNjc3ZDM4MDMwNTU0OGIwNDg5ZmU2NzVlZTIyYzRmNmU1MTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mUvDnNN_t6kyxN2BMp25LXj50iqdFi--AKx1FRQX_pw">
> 你好,使用template_meta.yaml模板出来后的短链接,放进openclash更新成功,但是运行时报如上截图中的错误

看错误提示这是OpenClash的问题，你应该搜索OpenClash怎么使用GEOSITE

**Comment by nitezs** [comment]
> 可否内置一批ACL4SSR模板列表让我们选择呢?

你可以自己修改ACL4SSR模板让程序读取，已经提供了加载外部模板的能力

**Comment by 277383761** [comment]
我自己弄了一个模板,也懂怎么使用了,但是生成的订阅在openclash里订阅失败,手动将短链中的内容粘贴成一个yaml文件放进openclash里点击切换提示配置文件测试失败....

**Comment by 277383761** [comment]
用内置的模板是成功了.用三方的模板没成功,看来还是我的问题.先谢作者大神了.

**Comment by 277383761** [comment]
改了好几个模板,保存成mini.yaml放入内置模板相同的位置.链接也生成,打开也有内容,但就是在openclash里提示配置错误.作者大大能否多内置几款模板哦.想要个带自动选择,故障转移,负载均衡 的...由于节点较多质量渗差不齐,才只能用这样的模板.

**Comment by nitezs** [comment]
> 改了好几个模板,保存成mini.yaml放入内置模板相同的位置.链接也生成,打开也有内容,但就是在openclash里提示配置错误.作者大大能否多内置几款模板哦.想要个带自动选择,故障转移,负载均衡 的...由于节点较多质量渗差不齐,才只能用这样的模板.

增加模板的工作交给社区，你可以把你的模板发出来给大家修改

**Comment by 277383761** [comment]
> > 改了好几个模板,保存成mini.yaml放入内置模板相同的位置.链接也生成,打开也有内容,但就是在openclash里提示配置错误.作者大大能否多内置几款模板哦.想要个带自动选择,故障转移,负载均衡 的...由于节点较多质量渗差不齐,才只能用这样的模板.
> 
> 增加模板的工作交给社区，你可以把你的模板发出来给大家修改

特来报喜的,我三方模板修改一个成功了.

**Comment by 277383761** [comment]
内个国家分组看着好不舒服,虽然可以勾上不输出,但还是希望预设就不输出.

**Comment by Rainbow609** [comment]
只用 '输出为 Node List' 其他部分自己写一个 proxy-providers 就行了，参考 [Meta](https://wiki.metacubex.one/example/conf/) 的写法，剩下的想要啥写啥。
