### ISSUE TITLE
请教如果是一个机场的两个不同订阅目前的处理策略是什么？

### ISSUE THREAD

**Issue by hausen1012** [nitezs/sub2clash#26]

**Comment by nitezs** [comment]
应该会被去除重复节点

**Comment by hausen1012** [comment]
不太懂机场的订阅是怎么回事，如果其中一个订阅流量用完了，那节点是不能用了还是怎么样？

**Comment by nitezs** [comment]
订阅流量用完节点自然是不能用了

**Comment by hausen1012** [comment]
那另外一个订阅还有流量呢？这种是怎么办

**Comment by nitezs** [comment]
上面说了重复节点会被去掉，所以不会同时有两个订阅的内容

**Comment by hausen1012** [comment]
意思就是不能把两个订阅当一个用是吗

**Comment by nitezs** [comment]
应该把两个订阅配置分开存，用完一个再切到另一个，我不是很懂把两个订阅放到同一个配置的目的

**Comment by tanmoumou252** [comment]
> 应该会被去除重复节点

不是有个`proxy_url#name` 节点重命名吗,所以是在重命名之前就被排除了吗

**Comment by nitezs** [comment]
> > 应该会被去除重复节点
> 
> 不是有个`proxy_url#name` 节点重命名吗,所以是在重命名之前就被排除了吗

执行顺序可以看这里的注释 [/api/handler/default.go](https://github.com/nitezs/sub2clash/blob/77484075839648f1ca0b5c2256cdb2e84abd20cb/api/handler/default.go#L107)
