### ISSUE TITLE
模板存在特定代码时会被自动消除掉

### ISSUE THREAD

**Issue by Depressboy** [nitezs/sub2clash#27]
在自定义模板时发现当存在如下代码时，生成的配置会自动消除掉此代码

GoogleCNProxyIP:
  type: http
  behavior: classical
  url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/GoogleCNProxyIP.yaml
  path: ./providers/rule-provider_GoogleCNProxyIP.yaml
  interval: 86400
    
ChinaIp:
  type: http
  behavior: classical
  url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/ChinaIp.yaml
  path: ./providers/rule-provider_ChinaIp.yaml
  interval: 86400

下面的代码能正常生成
  - RULE-SET,ChinaCompanyIp,🎯 全球直连,no-resolve
  - RULE-SET,GoogleCNProxyIP,🚀 节点选择,no-resolve

**Comment by nitezs** [comment]
提供一下完整模板

**Comment by Depressboy** [comment]
不好意思，是我没有配置完整。完整的模板代码应该是

rule-providers:
  GoogleCNProxyIP:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/GoogleCNProxyIP.yaml
    path: ./providers/rule-provider_GoogleCNProxyIP.yaml
    interval: 86400
    
  ChinaIp:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/ChinaIp.yaml
    path: ./providers/rule-provider_ChinaIp.yaml
    interval: 86400

贸然打开issue实在抱歉
