### ISSUE TITLE
v2rayn 导出的Hysteria 2 的 URI 格式转换后会，name为空，导致多个hy节点只保留了一个

### ISSUE THREAD

**Issue by ycj1379** [nitezs/sub2clash#28]
测试订阅为：
hysteria2://password@example.com:443/?sni=real.example.com&alpn=h3&insecure=0#example-name
hysteria2://letmein@example.com/?insecure=1&obfs=salamander&obfs-password=gawrgura&pinSHA256=deadbeef&sni=real.example.com

**Comment by nitezs** [comment]
https://github.com/nitezs/sub2clash/commit/aa9e102a8191b6082adcc515e1095d49be42b443
