### ISSUE TITLE
Trojan + ws 转换为meta配置出现错误

### ISSUE THREAD

**Issue by Asseken** [nitezs/sub2clash#29]
Trojan + ws 转换为clash.meta  无法使用，并且配置出现丢失

**Comment by nitezs** [comment]
能给一个测试链接吗

**Comment by Asseken** [comment]
> 能给一个测试链接吗
trojan://Abse64hhjewrs@test.com:8443?type=ws&path=%2Fx&host=test.com&security=tls&fp=&alpn=http%2F1.1&sni=test.com#test
这是订阅转换的配置
![image](https://github.com/nitezs/sub2clash/assets/72454306/ad95a98a-2ccd-40c1-a7ab-2bdd6137e309)
![image](https://github.com/nitezs/sub2clash/assets/72454306/eb8fd81b-cb89-4d97-be85-cc1ee266d486)
缺失后半部分配置

**Comment by nitezs** [comment]
https://github.com/nitezs/sub2clash/commit/48dece2a51db9f8f008790d4a04946b482f4e4a9

**Comment by Asseken** [comment]
> 能给一个测试链接吗

这是meta官方的配置
  - name: trojan-ws
    server: server
    port: 443
    type: trojan
    password: "example"
    network: ws
    sni: example.com
    # skip-cert-verify: true
    # fingerprint: xxxx
    udp: true
    # ws-opts:
    #   path: /path
    #   headers:
    #     Host: example.com
    #   v2ray-http-upgrade: false

**Comment by nitezs** [comment]
> [48dece2](https://github.com/nitezs/sub2clash/commit/48dece2a51db9f8f008790d4a04946b482f4e4a9)

我已经尝试修正了，你可以试试解析结果是否符合预期

**Comment by Asseken** [comment]
> > [48dece2](https://github.com/nitezs/sub2clash/commit/48dece2a51db9f8f008790d4a04946b482f4e4a9)
> 
> 我已经尝试修正了，你可以试试解析结果是否符合预期

编译后正常，转换的Trojan+ws节点可以使用
