### ISSUE TITLE
新增功能征集

### ISSUE THREAD

**Issue by nitezs** [nitezs/sub2clash#3]
有想要增加的功能可以在这里提出

**Comment by OrangeCatSleepless** [comment]
支持 sub-web 的 "输出为 Node List" 功能

**Comment by nitezs** [comment]
> 支持 sub-web 的 "输出为 Node List" 功能

只输出节点吗

**Comment by OrangeCatSleepless** [comment]
> > 支持 sub-web 的 "输出为 Node List" 功能
> 
> 只输出节点吗

对 这样的

![image](https://github.com/nitezs/sub2clash/assets/58691431/42172808-9d9e-456b-95f2-91970a3faa37)

**Comment by nitezs** [comment]
> > > 支持 sub-web 的 "输出为 Node List" 功能
> > 
> > 
> > 只输出节点吗
> 
> 对 这样的
> 
> ![image](https://user-images.githubusercontent.com/58691431/270263551-42172808-9d9e-456b-95f2-91970a3faa37.png)

我在dev分支增加了这个功能，但是我不太清楚每个节点是否一定要像图中这样一行输出

**Comment by OrangeCatSleepless** [comment]
> > > > 支持 sub-web 的 "输出为 Node List" 功能
> > > 
> > > 
> > > 只输出节点吗
> > 
> > 
> > 对 这样的
> > ![image](https://user-images.githubusercontent.com/58691431/270263551-42172808-9d9e-456b-95f2-91970a3faa37.png)
> 
> 我在dev分支增加了这个功能，但是我不太清楚每个节点是否一定要像图中这样一行输出 如果你不想构建 dev 分支，这里有一个 Demo https://nite07.com/sub/

软件都能读出来，一行输出的话，节点多的情况下看起来简洁点，区别不是很大，都可以，试了一下 demo 效果不错

**Comment by OrangeCatSleepless** [comment]
有可能实现这个功能吗？
  
   对多个订阅链接的情况下在生成的对应节点前加上来自哪个订阅链接
  
  比如说
  同时填写了2个订阅链接 订阅1中有节点 香港 订阅2中也有节点 香港
  
  最终生成的配置文件里 节点重命名的时候会带上 订阅1-香港 订阅2-香港
  
  具体要重命名成什么可以通过填写订阅链接时 在链接后面使用特殊符号来判断
  
  类似这样
  https://nite07.com/sub/#订阅1
  https://nite07.com/#订阅2

**Comment by nitezs** [comment]
> 有可能实现这个功能吗？
> 
> 对多个订阅链接的情况下在生成的对应节点前加上来自哪个订阅链接
> 
> 比如说 同时填写了2个订阅链接 订阅1中有节点 香港 订阅2中也有节点 香港
> 
> 最终生成的配置文件里 节点重命名的时候会带上 订阅1-香港 订阅2-香港
> 
> 具体要重命名成什么可以通过填写订阅链接时 在链接后面使用特殊符号来判断
> 
> 类似这样 [https://nite07.com/sub/#订阅1](https://nite07.com/sub/#%E8%AE%A2%E9%98%851) [https://nite07.com/#订阅2](https://nite07.com/#%E8%AE%A2%E9%98%852)

可以，之后有空会加上

**Comment by nitezs** [comment]
> 能提供各个国家分开的关键字吗，方便书写自定义模板，比如hk jp usa这样

我没有理解你的意思

**Comment by echowiz** [comment]
[模板](https://github.com/nitezs/sub2clash#%E6%A8%A1%E6%9D%BF)
可以通过变量自定义模板中的策略组代理节点 解释的不太清楚，可以参考下方默认模板

<all> 为添加所有节点
<countries> 为添加所有国家策略组

就是现在有所有国家的策略组，能不能在提供下单个国家的策略组，方便自定义

**Comment by nitezs** [comment]
> [模板](https://github.com/nitezs/sub2clash#%E6%A8%A1%E6%9D%BF) 可以通过变量自定义模板中的策略组代理节点 解释的不太清楚，可以参考下方默认模板
> 
> all 为添加所有节点 countries 为添加所有国家策略组
> 
> 就是现在有所有国家的策略组，能不能在提供下单个国家的节点组，方便自定义
> 
> 比如：我想给 香港节点，分别设置 延时优先 故障转移 负载均衡 三种策略来切换，这样就需要使用提取出来的香港节点这个组，现在只有所有国家的不能单独使用某一个地区组

明白了，之后有空会加上

**Comment by nitezs** [comment]
> [模板](https://github.com/nitezs/sub2clash#%E6%A8%A1%E6%9D%BF) 可以通过变量自定义模板中的策略组代理节点 解释的不太清楚，可以参考下方默认模板
> 
> all 为添加所有节点 countries 为添加所有国家策略组
> 
> 就是现在有所有国家的策略组，能不能在提供下单个国家的节点组，方便自定义
> 
> 比如：我想给 香港节点，分别设置 延时优先 故障转移 负载均衡 三种策略来切换，这样就需要使用提取出来的香港节点这个组，现在只有所有国家的不能单独使用某一个地区组

dev 分支添加了这个功能

**Comment by nitezs** [comment]
> 有可能实现这个功能吗？
> 
> 对多个订阅链接的情况下在生成的对应节点前加上来自哪个订阅链接
> 
> 比如说 同时填写了2个订阅链接 订阅1中有节点 香港 订阅2中也有节点 香港
> 
> 最终生成的配置文件里 节点重命名的时候会带上 订阅1-香港 订阅2-香港
> 
> 具体要重命名成什么可以通过填写订阅链接时 在链接后面使用特殊符号来判断
> 
> 类似这样 [https://nite07.com/sub/#订阅1](https://nite07.com/sub/#%E8%AE%A2%E9%98%851) [https://nite07.com/#订阅2](https://nite07.com/#%E8%AE%A2%E9%98%852)

dev 分支添加了这个功能

**Comment by OrangeCatSleepless** [comment]
> > 有可能实现这个功能吗？
> > 对多个订阅链接的情况下在生成的对应节点前加上来自哪个订阅链接
> > 比如说 同时填写了2个订阅链接 订阅1中有节点 香港 订阅2中也有节点 香港
> > 最终生成的配置文件里 节点重命名的时候会带上 订阅1-香港 订阅2-香港
> > 具体要重命名成什么可以通过填写订阅链接时 在链接后面使用特殊符号来判断
> > 类似这样 [https://nite07.com/sub/#订阅1](https://nite07.com/sub/#%E8%AE%A2%E9%98%851) [https://nite07.com/#订阅2](https://nite07.com/#%E8%AE%A2%E9%98%852)
> 
> dev 分支添加了这个功能

效果很棒👍

**Comment by OrangeCatSleepless** [comment]
能支持Hysteria和Reality协议的节点转换吗

**Comment by Rainbow609** [comment]
问下大家，有没有能自动删除失效节点的，订阅了几个白嫖的机场，蛮多失效节点的，想通过订阅转换先干掉那些不能用的

**Comment by ycj1379** [comment]
希望增加重复节点自动增加数字后缀名，不然有些重复名称的会导致错误

**Comment by nitezs** [comment]
> 问下大家，有没有能自动删除失效节点的，订阅了几个白嫖的机场，蛮多失效节点的，想通过订阅转换先干掉那些不能用的

去除失效节点的工作不应该由订阅转换程序负责，应该找其他专门解决这个问题的程序

**Comment by nitezs** [comment]
> 希望增加重复节点自动增加数字后缀名，不然有些重复名称的会导致错误

现在就是这样处理重名节点的，你遇到了什么错误

**Comment by hm-Private** [comment]
没有搭建教程么😂

**Comment by nitezs** [comment]
> 没有搭建教程么😂

 直接运行程序或者用docker就可以了，很简单所以没写教程

**Comment by hm-Private** [comment]
> > 没有搭建教程么😂
> 
> 
> 
>  直接运行程序或者用docker就可以了，很简单所以没写教程

小白，没教程不会往服务器捣鼓，最好支持宝塔😂

**Comment by nitezs** [comment]
> > > 没有搭建教程么😂
> > 
> > 
> > 直接运行程序或者用docker就可以了，很简单所以没写教程
> 
> 小白，没教程不会往服务器捣鼓，最好支持宝塔😂

宝塔应该是有docker管理器的，我没怎么用过

**Comment by pizixi** [comment]
能加下udp:true 参数吗

**Comment by nitezs** [comment]
> 能加下udp:true 参数吗

啥意思

**Comment by pizixi** [comment]
![image](https://github.com/nitezs/sub2clash/assets/56673215/dbf5eafc-fd69-4182-8991-8c75314332d0)

**Comment by ycj1379** [comment]
> > 希望增加重复节点自动增加数字后缀名，不然有些重复名称的会导致错误
> 
> 现在就是这样处理重名节点的，你遇到了什么错误

我的运行环境是二进制文件，默认的参数运行，模版也是默认的，客户端类型选择Clash.Meta，生成的配置中重复名称的节点未增加后缀，使用clash verge导入会提示节点名称HK1重复
![捕获](https://github.com/nitezs/sub2clash/assets/4538954/2daee9ee-139c-483f-872b-60e65164bf4a)

**Comment by nitezs** [comment]
> > > 希望增加重复节点自动增加数字后缀名，不然有些重复名称的会导致错误
> > 
> > 
> > 现在就是这样处理重名节点的，你遇到了什么错误
> 
> 我的运行环境是二进制文件v0.0.7，默认的参数运行，模版也是默认的，客户端类型选择Clash.Meta，生成的配置中重复名称的节点未增加后缀，使用clash verge导入会提示节点名称HK1重复，订阅为v2ray通用订阅格式，节点名称带HK01、02。
> 
> ![捕获](https://private-user-images.githubusercontent.com/4538954/310098592-2daee9ee-139c-483f-872b-60e65164bf4a.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5NzA0NzgsIm5iZiI6MTcwOTk3MDE3OCwicGF0aCI6Ii80NTM4OTU0LzMxMDA5ODU5Mi0yZGFlZTllZS0xMzljLTQ4M2YtODcyYi02MGU2NTE2NGJmNGEuUE5HP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDlUMDc0MjU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzkzMTUxMzAwMGM5Mjk3MTE4YmI4YTkxMjI2MjIxM2FmYjA2MjE1NTczNThkNjFkYjg3NjRmMDc0ZWYzMmE4MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.oiolxtaVIjAKbwHgdtXtJkTWb0fdJ5je_MU0tFnhc48)

dev版的docker镜像应该修正了这个问题，你可以试试
