### ISSUE TITLE
请问如何添加一个自定义的节点呢？

### ISSUE THREAD

**Issue by qiaoyun680** [nitezs/sub2clash#31]
我期望在所订阅的机场列表之中，增添一个属于我自己的 wireguard 节点呢？那么请问，我应当怎样进行正确的操作呢？是在模板中的proxies:添加吗？

**Comment by nitezs** [comment]
是的

**Comment by qiaoyun680** [comment]
> 是的

谢谢回答，还有就是通过docker compose启动之后 选择了客户端类型是clash meta后，访问配置链接提示“加载模板失败: 模板文件不存在“，是由于什么原因呀？

**Comment by nitezs** [comment]
docker-compose.yml 同目录下应该有 templates 目录，确保里面有这些文件 https://github.com/nitezs/sub2clash/tree/main/templates
或者在Web页面自己指定模板的路径或链接

**Comment by qiaoyun680** [comment]
> docker-compose.yml 同目录下应该有 templates 目录，确保里面有这些文件 https://github.com/nitezs/sub2clash/tree/main/templates 或者在Web页面自己指定模板的路径或链接

在页面上的规则那里，新增之后例如
![image](https://github.com/nitezs/sub2clash/assets/10334189/b8b85f0b-8c2a-4445-9128-f3390c8c34f5)
配置文件有些问题 输出true
![Uploading image.png…]()

**Comment by qiaoyun680** [comment]
> 是的
我在模板文件中新增了一条
proxies:
  - name: wg
    type: wireguard
    private-key: IK2xqtD2+cj8mNG/5r1hg2YYND0M***********
    server: ***********
    port: 51820
    ip: 192.168.168.2
    public-key: C7E7pAC/La54/So9vs6bWpWIMX***********
    allowed-ips: ['192.168.0.0/16']
    udp: true
生成的配置文件为
proxies:
    - null

**Comment by nitezs** [comment]
> > 是的
> 
> 我在模板文件中新增了一条 proxies:
> 
>     * name: wg
>       type: wireguard
>       private-key: IK2xqtD2+cj8mNG/5r1hg2YYND0M***********
>       server: ***********
>       port: 51820
>       ip: 192.168.168.2
>       public-key: C7E7pAC/La54/So9vs6bWpWIMX***********
>       allowed-ips: ['192.168.0.0/16']
>       udp: true
>       生成的配置文件为
>       proxies:
>       
>       * null

0946412ea7a53f42a7aa3bd32ea2995b747fd501

**Comment by nitezs** [comment]
> > docker-compose.yml 同目录下应该有 templates 目录，确保里面有这些文件 https://github.com/nitezs/sub2clash/tree/main/templates 或者在Web页面自己指定模板的路径或链接
> 
> 在页面上的规则那里，新增之后例如 ![image](https://private-user-images.githubusercontent.com/10334189/332301829-ace49aa7-9475-467d-8813-1bee13c74e9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyNzY4NjYsIm5iZiI6MTcxNjI3NjU2NiwicGF0aCI6Ii8xMDMzNDE4OS8zMzIzMDE4MjktYWNlNDlhYTctOTQ3NS00NjdkLTg4MTMtMWJlZTEzYzc0ZTlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDA3MjkyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxM2ZlMWE4NGUzZGRlY2JkMjBlY2Q3Mjg1NmNiMzIzNWMxMTZiYzA2MDE2ZDg5ODE2MjBjNmI5NjE1N2JmOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rWQNSdrE2DoliApI23Sou28e32r42bUIdSmvLcql-aM) 配置文件有些问题 输出true ![image](https://private-user-images.githubusercontent.com/10334189/332301710-c30d7e8d-23a8-4ea1-836b-c760451b960e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyNzY4NjYsIm5iZiI6MTcxNjI3NjU2NiwicGF0aCI6Ii8xMDMzNDE4OS8zMzIzMDE3MTAtYzMwZDdlOGQtMjNhOC00ZWExLTgzNmItYzc2MDQ1MWI5NjBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDA3MjkyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiYTFiODcwYzZiODI5YTcyNmZkMGYxZjI3Mzk1MGRkYTQ3MjVhMjc2M2E3YzkxMWYwMzcxYmVhODg1ZDk3M2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Gl9cHyqjZeq3oNUiycqBt06SF9Dp_uGeFV-Hm3JhcZw)

98bca0a7ac18b010995b126e06421c1d9480c62b

**Comment by qiaoyun680** [comment]
感谢~
![013BB54A](https://github.com/nitezs/sub2clash/assets/10334189/a7193fc2-2fe0-4026-89f4-25f371740358)
