### ISSUE TITLE
无法导入hysteria2节点

### ISSUE THREAD

**Issue by denny0810** [nitezs/sub2clash#33]
尝试转换如下链接
https://[raw.githubusercontent.com/yyyr-otz/tele-providers-collector/master/script/raw/protocols/hysteria.txt](https://raw.githubusercontent.com/yyyr-otz/tele-providers-collector/master/script/raw/protocols/hysteria.txt)
生成的链接内只包含hysteria的节点。
请看下是该如何解决。 谢谢

**Comment by nitezs** [comment]
Pre-release 版本中修复了
