### ISSUE TITLE
使用最新的alpha.4版本在更新订阅时会出现奇怪节点，且短连接解析有问题

### ISSUE THREAD

**Issue by Depressboy** [nitezs/sub2clash#36]
1、使用最新的alpha.4版本在更新订阅时会出现“去除13条不合适线路”字样的节点，如图所示

![搜狗截图20240717225851](https://github.com/user-attachments/assets/cb126b1f-6737-42ed-a225-bcffa214ecfc)

2、短连接解析是提示“获取短连接失败，请检查密码”，但我并没有设置密码，且短连接可以正常获取节点

![搜狗截图20240717230330](https://github.com/user-attachments/assets/87c0a173-5ba8-419e-bc1c-c474546dff13)
![搜狗截图20240717230357](https://github.com/user-attachments/assets/d211ac59-9ff1-4547-a48e-b92f9083cf8d)

**Comment by Depressboy** [comment]
第一个问题经过查找应该是机场的问题，机场有个节点名称是“去除13条不合适线路”

**Comment by nitezs** [comment]
只有加密码的短链可以被解析。这里的提示文字有些问题，已修改。
