### ISSUE TITLE
订阅转换后名称失效

### ISSUE THREAD

**Issue by LY102483** [nitezs/sub2clash#37]
假如我有一个节点信息如下
`- { name: '🇩🇪德国 | 高速专线-hy2', server: 138.3.222.157, port: 37000, ports: 37000-39000, mport: 37000-39000, udp: true, skip-cert-verify: true, sni: api.push.apple.com, type: hysteria2, password: ffeb3435-942a-4590-a22e-57a31eeff6d2 }`
但是被转换后直接显示为了1,2,3这样的特殊名称。
![Snipaste_2024-08-03_17-27-28](https://github.com/user-attachments/assets/b5316cce-8209-4927-ae9e-4bdc554c0867)

**Comment by nitezs** [comment]
节点的原链接是什么格式的？
目前hysteria2解析节点是根据链接中的 `name` 参数

**Comment by LY102483** [comment]
原订阅链接返回的结果应该是被base64编码的，在你的程序中，好像只有hy2的节点名称不能被解析，其他类型的节点名称是正确的
![image](https://github.com/user-attachments/assets/962a9e6f-440c-4378-8a54-914616205af2)

**Comment by nitezs** [comment]
看起来节点名是用 `#` 号作为分割符的，我兼容一下。
