### ISSUE TITLE
【提议】能否增加udp和skip-cert-verify等配置的处理

### ISSUE THREAD

**Issue by ethanxyzhu** [nitezs/sub2clash#38]
我有些机场节点需要skip-cert-verify，不知道该如何配置
![图片](https://github.com/user-attachments/assets/2ba48246-1d38-4a63-bcc4-256798acfb47)

**Comment by nitezs** [comment]
给一个示例

**Comment by ethanxyzhu** [comment]
我觉得可以像类似于[给节点名称添加自定义后缀](https://github.com/nitezs/sub2clash/issues/3#issuecomment-1733145030)这样，为订阅链接设置udp和skip-cert-verify的开关
![图片](https://github.com/user-attachments/assets/c06ae3dd-c18b-4e58-8730-f5ee1e7b6b8c)
您有空的话可以考虑考虑

**Comment by nitezs** [comment]
我的意思是这些参数应该是节点链接中提供的
