### ISSUE TITLE
新版启动失败

### ISSUE THREAD

**Issue by OrangeCatSleepless** [nitezs/sub2clash#6]
0.0.4 和 0.0.5 直接启动会失败,需要先启动 0.0.3 自动创建配置文件之后再启动 否则无法成功启动 旧版本无这个问题

**Comment by nitezs** [comment]
感谢反馈，等下重发一版

**Comment by nitezs** [comment]
[v0.0.5-fix](https://github.com/nitezs/sub2clash/releases/tag/v0.0.5-fix)
这一版应该没有问题了

**Comment by OrangeCatSleepless** [comment]
> [v0.0.5-fix](https://github.com/nitezs/sub2clash/releases/tag/v0.0.5-fix) 这一版应该没有问题了

完美👍
